
  
version: '3.9'

services:
  db:
    image: postgres:13
    container_name: gama-academy
    ports:
      - '5433:5432'
    environment:
      - POSTFRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_MULTIPLE_DATABASES=gama-academy, gama-academy-test
    volumes: 
      - pgdata:/data/postgres
    networks:
      - net-gama

  datadoghq:
    container_name: dd-agent
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
        - '/proc/:/host/proc/:ro'
        - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    environment:
        - DD_API_KEY=${DD_API_KEY}
        - DD_SITE=us5.datadoghq.com
        - DD_APM_ENABLED=true
        - DD_APM_NON_LOCAL_TRAFFIC=true
    ports:
      - '8126:8126'
    image: 'gcr.io/datadoghq/agent:7'

volumes: 
  pgdata:
    driver: local

networks:
  net-gama:
    ipam:
      driver: default
      config:
        - subnet: "172.14.218.0/24"