
  
version: '3.9'

services:
  db:
    image: postgres:13
    container_name: gama-academy
    ports:
      - '5433:5432'
    environment:
      - POSTFRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=gama-academy
    volumes: 
      - pgdata:/data/postgres
    networks:
      - net-gama

volumes: 
  pgdata:
    driver: local

networks:
  net-gama:
    ipam:
      driver: default
      config:
        - subnet: "172.14.218.0/24"